networks:
  hw14-cdn:

services:
  load_balancer1:
    image: openresty/openresty:alpine
    container_name: load_balancer1
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
      - ./loadbalancer/loadbalancer1_logs:/var/log/nginx
    networks: &NETWORKS
      - hw14-cdn
  
  load_balancer2:
    image: openresty/openresty:alpine
    container_name: load_balancer2
    ports:
      - "81:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
      - ./loadbalancer/loadbalancer2_logs:/var/log/nginx
    networks: *NETWORKS
  
  node1:
    image: openresty/openresty:alpine
    container_name: node1
    ports:
      - "82:80"
    volumes:
      - ./node/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./node/node1_logs:/var/log/nginx
      - ./static:/var/www/static
    networks: *NETWORKS
  
  node2:
    image: openresty/openresty:alpine
    container_name: node2
    volumes:
      - ./node/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./node/node2_logs:/var/log/nginx
      - ./static:/var/www/static
    networks: *NETWORKS
  
  node3:
    image: openresty/openresty:alpine
    container_name: node3
    volumes:
      - ./node/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./node/node3_logs:/var/log/nginx
      - ./static:/var/www/static
    networks: *NETWORKS
  
  node4:
    image: openresty/openresty:alpine
    container_name: node4
    volumes:
      - ./node/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./node/node4_logs:/var/log/nginx
      - ./static:/var/www/static
    networks: *NETWORKS
  