version: "3.8"

services:
  dotnet:
    container_name: dotnet-service-webapi
    build:
      context: ./dotnet-service/webapi
      dockerfile: Dockerfile
    expose:
      - 8080
    depends_on: 
      - mongodb
      - elasticsearch

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "mongodbdata:/data/db"
      - "mongodbconfig:/data/configdb"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  nginx:
    container_name: nginx
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - dotnet

volumes:
  mongodbdata:
  mongodbconfig:
    