services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      timeout: 30s
      interval: 10s
      start_period: 0s
      retries: 30
    volumes:
      - mongodb_data_hw24:/data/db
      - mongodb_data_hw24_config:/data/configdb

volumes:
  mongodb_data_hw24:
  mongodb_data_hw24_config:
