services: 
  
  redis-1:
      image: redis:latest
      container_name: redis-1
      command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "6379"]
      ports:
        - "6379:6379"
      volumes:
        - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
        - redis_1_data_hw12:/data
      environment:
        - REDIS_REPLICATION_MODE=master
      healthcheck:
        test: ["CMD", "redis-cli", "-p", "6379", "ping"]
        interval: 5s
        timeout: 5s
        retries: 5
        
  redis-2:
      image: redis:latest
      container_name: redis-2
      command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--port", "6380"]
      ports:
        - "6380:6380"
      depends_on: 
        redis-1:
          condition: service_healthy
      volumes:
        - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
        - redis_2_data_hw12:/data
      environment:
        - REDIS_REPLICATION_MODE=slave
        - REDIS_MASTER_HOST=redis-1
        - REDIS_MASTER_PORT=6379
      healthcheck:
        test: ["CMD", "redis-cli", "-p", "6380", "ping"]
        interval: 5s
        timeout: 5s
        retries: 5
  
  sentinel-1:
      image: redis:latest
      container_name: sentinel-1
      command: ["redis-server", "/usr/local/etc/redis/sentinel.conf", "--sentinel"]
      ports:
        - "26379:26379"
      depends_on: 
        redis-1:
          condition: service_healthy
        redis-2:
          condition: service_healthy
      volumes:
        - ./configs/sentinel.conf:/usr/local/etc/redis/sentinel.conf
        - sentinel_1_data_hw12:/data
      environment:
        - REDIS_MASTER_HOST=redis-1
        - REDIS_MASTER_PORT=6379
        - REDIS_MASTER_NAME=mymaster

volumes: 
  redis_1_data_hw12:
  redis_2_data_hw12:
  sentinel_1_data_hw12:
  