version: '3.8'

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: "1G"
                reservations: # Same as limits to be more predictable
                    cpus: "1.0"
                    memory: "1G"

volumes:
    pg_data:
