filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.modules:
  - module: mysql
    error:
      enabled: true
      var.paths: ["/var/log/mysql/error.log*"]
    slowlog:
      enabled: true
      var.paths: ["/var/log/mysql/slow-mysql-query.log*"]

output.logstash:
  hosts: ["logstash:5044"]

#setup.dashboards:
#  enabled: true

#setup.kibana:
#  host: "http://kibana:5601"
#  username: ${ELASTICSEARCH_USERNAME}
#  password: ${ELASTICSEARCH_PASSWORD}

#xpack.monitoring:
#  enabled: true
#  elasticsearch: 