services: 
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'hw9'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'User0123456789'
      MYSQL_ROOT_PASSWORD: 'Root0123456789'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
