name: workflow.yml
on:
  push:
    branches:
      - 'hw25-ci-cd/**'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore Dependencies
        working-directory: './hw25-ci-cd/src'
        run: dotnet restore
      - name: Run Unit Tests
        working-directory: './hw25-ci-cd/src'
        run: dotnet test --filter FullyQualifiedName\!~IntegrationTests

  integration-tests:
    name: Integration Tests
    needs:
      - unit-tests
    runs-on: ubuntu-latest
    services: 
      mongo:
        image: mongo:7.0.11
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore Dependencies
        working-directory: './hw25-ci-cd/src'
        run: dotnet restore
      - name: Run Integration Tests
        working-directory: './hw25-ci-cd/src'
        run: dotnet test --filter FullyQualifiedName\!~UnitTests
